version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/data/www/meeting:/app"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - php
    php:
        image: meeting/php:8.1-fpm
        restart: always
        #command:
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "/data/www/meeting:/app"
    composer:
        image: "composer"
        volumes:
            - "/data/www/meeting:/app"
        command: install
    redis:
        image: "redis"
        restart: always
    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8080:80"
        restart: always
