version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - "./nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
            - ./web:/app
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - php
    php:
        build: ./php
        restart: always
        volumes:
            - "./php/config/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/app
    composer:
        image: "composer"
        volumes:
            - ./web:/app
        command: install
    redis:
        image: "redis"
        restart: always
    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8080:80"
        restart: always
